export const ACCEPT_PROVINCES = ['79', '75', '74', '72', '80']
export const ROLES = {
    USER: 'ROLE_USER',
    ADMIN: 'ROLE_ADMIN',
    FULL_CONTROL:"FULL_CONTROL",
    SUPER_ACCOUNT: 'SUPER_ACCOUNT',
    PROMOTION_UPDATE:'PROMOTION_UPDATE',
    OUTFIT_UPDATE:'OUTFIT_UPDATE',
}